AWSTemplateFormatVersion: 2010-09-09
Resources:
  # Got this from AWS official snippets https://docs.aws.amazon.com/es_es/AWSCloudFormation/latest/UserGuide/quickref-s3.html
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
    DeletionPolicy: Retain
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Id: MyPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join 
              - ''
              - - 'arn:aws:s3:::'
                - !Ref S3Bucket
                - /*
      Bucket: !Ref S3Bucket
  # Got this from AWS official snippets https://docs.aws.amazon.com/es_es/AWSCloudFormation/latest/UserGuide/quickref-cloudfront.html
  myDistribution:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        Origins:
        - DomainName: !Join
          - ''
          - - !Ref S3Bucket
            - .s3-website-
            - !Ref "AWS::Region"
            - .amazonaws.com
          Id: myCustomOrigin
          CustomOriginConfig:
            HTTPPort: '80'
            HTTPSPort: '443'
            OriginProtocolPolicy: http-only
          OriginShield:
            Enabled: true
            OriginShieldRegion: !Ref "AWS::Region"
        DefaultCacheBehavior:
          AllowedMethods: 
            - GET
            - HEAD
          Compress: true
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          TargetOriginId: myCustomOrigin
          ViewerProtocolPolicy: redirect-to-https
        Enabled: true
Outputs:
  WebsiteURL:
    Value: !GetAtt 
      - S3Bucket
      - WebsiteURL
    Description: URL for website hosted on S3
  S3BucketSecureURL:
    Value: !Join 
      - ''
      - - 'https://'
        - !GetAtt 
          - S3Bucket
          - DomainName
    Description: Name of S3 bucket to hold website content
  BucketURL:
    Value: !Join
      - ''
      - - 's3://'
        - !Ref S3Bucket
  CFURL:
    Value: !GetAtt
      - myDistribution
      - DomainName
